#!/bin/sh
command -v python 2>&1 >/dev/null && { PYTHON=python; }
command -v python3 2>&1 >/dev/null && { PYTHON=python3; }
command -v python3.4 2>&1 >/dev/null && { PYTHON=python3.4; }
command -v python3.5 2>&1 >/dev/null && { PYTHON=python3.5; }
command -v python3.6 2>&1 >/dev/null && { PYTHON=python3.6; }
$PYTHON /usr/local/share/halibot/main.py $@
